#!/bin/bash
#
# squid启动服务
#
# chkconfig:   - 85 15 
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO
path="/usr/local/webserver"


start(){
    for list in $(ls $path|grep squid)
    do
        pro=${path}/$list
        echo -n $"Starting $pro: " 
        $pro/sbin/squid
        port=$(awk '$1 == "acl" && $2 == "accel_8080" {print $NF}' $pro/etc/squid.conf)
        netstat -ntlp|grep -q $port || sleep 2 && $pro/sbin/squid
        echo "[ok]"
    done
}

case $1 in
start)
	start
;;
esac
exit 0
